import type { Metadata } from 'next';
import { type ReactNode } from 'react';

import { Roboto } from 'next/font/google';

import '@/shared/styles/globals.css';

import { Header } from '@/widgets/Header/ui/Header';
import { Main } from '@/shared/ui/Main/Main';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Gmail Next App',
  description: 'Generated by create next app',
  icons: '/icons/header-icons/gmail-logo.svg',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased`}>
        <Header />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
